### ISSUE TITLE
error messages look bad and unreadable

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-http-gw#104]
```
neofs-http-gw/app.go:123        failed to create connection pool        {"error": "failed to create neofs session token for client unknown: transport error: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup edge02.testcdn.fs.neo.org on 67.207.67.2:53: no such host\""}
```
```
neofs-http-gw/app.go:123        failed to create connection pool        {"error": "failed to create neofs session token for client unknown: transport error: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 1.1.1.1:8080: i/o timeout\""}
```

**Comment by alexvanin** [comment]
Any suggestions besides changing zap logger format?

**Comment by aprasolova** [comment]
Proposals:
- print stacktrace in few strings (consider '\n''s)
- print only the last message as it contains more sense

**Comment by 532910** [comment]
- print delimiter

**Comment by alexvanin** [comment]
> print stacktrace in few strings (consider '\n''s)

I doubt you'll like it if you try to grep some message in console and it will be part of multi line log record.

> print only the last message as it contains more sense

These errors are encapsulated, so it is useful for tracing the origin of error. In the example above, gRPC transport output may be quite useless, I agree. It should be gone with status codes adoption, but even without it we can try to avoid `transport error: rpc error: code = Unavailable desc` substring, I suppose. But that's it.

**Comment by 532910** [comment]
- reverse the order

**Comment by alexvanin** [comment]
> print delimiter

`\t` used as delimiter for date, caller (`neofs-http-gw/app.go:123 `) and message. It can be change to whitespace, but it makes harder to read. 

```
2021-11-18T13:27:30.007Z neofs-http-gw/app.go:123 failed to create connection pool {"error": "failed to create neofs session token for client unknown: transport error: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp: lookup edge02.testcdn.fs.neo.org on 67.207.67.2:53: no such host\""}
```

We can drop the caller field. Or enable it only in `DEBUG` log level or something like that.

**Comment by alexvanin** [comment]
Stale issue. Closed until we figure out what can be improved besides message text.
