### ISSUE TITLE
System headers response format

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-http-gw#111]
Currently using `http-gw` we can set expiration epoch using header `X-Attribute-Neofs-Expiration-Epoch`.
But when we get object the header will be `X-Attribute-__NEOFS__EXPIRATION_EPOCH`. Shouldn't we change this behavior?

**Comment by realloc** [comment]
Yes, we need to properly handle the backward translation. Moreover `X-Attribute-__NEOFS__EXPIRATION_EPOCH` is not a valid header name.
