### ISSUE TITLE
Different heading formation in `GET` and `HEAD`

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-http-gw#125]
Seems like [GET](https://github.com/nspcc-dev/neofs-http-gw/blob/2110e924e907ec84e56133f14ad18560f7f2b16f/downloader/download.go#L178) and [HEAD](https://github.com/nspcc-dev/neofs-http-gw/blob/2110e924e907ec84e56133f14ad18560f7f2b16f/downloader/head.go#L60) handlers form identity headers differently.

**Comment by KirillovDenis** [comment]
I'm not sure this is a bug because `r.Response.Header.Set` function normalize header key (if `disableNormalizing` isn't set). But I agree we should use the same keys (probable we should define constants for that)

**Comment by KirillovDenis** [comment]
It turns out we disabled normalization.

I suggest the reason is reverse proxy:
> Disabled header names' normalization may be useful only for proxying
> incoming requests to other servers expecting case-sensitive
> header names. See https://github.com/valyala/fasthttp/issues/57
> for details.
