### ISSUE TITLE
Use `Accept` header from the request to transform response

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-http-gw#168]
There is use case when web applications read config files from NeoFS. It might be not so easy to parse structured data like YAML config.

HTTP Gateway can use `Accept` header to transform YAML file. We can start with JSON encoding.

**Comment by KirillovDenis** [comment]
I'm not sure we should support this. As I understand `Accept` header is for transform models representation that is formed by backend. In out case we will transform the raw payload of objects. It seems a little odd.
