### ISSUE TITLE
 Make version output the same as in neofs-node

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-http-gw#169]
HTTP Gateway currently displays its version like:
```
$ neofs-http-gw --version
NeoFS HTTP Gateway v0.19.0-4-g9c892ed
```
We need to make it like in neofs-node, like:
```
$ neofs-node --version
Version: v0.28.3-62-g8ab72eb4 
Build: 2022-07-05T21:45:30+00:00 
Debug: false
```
Maybe we want to add Component: NeoFS HTTP Gateway also, to help robots in parsing output.
Adding debug build is not required now, but I'd be glad if we can make the whole stack behave the same way.

**Comment by roman-khimov** [comment]
`Build` was dropped intentionally in 6c73296012b8031eb02d7303f5d547b6657a9728, btw.

**Comment by realloc** [comment]
Reproducible builds is a wonderful point. Let' make Build info an option, like Debug? We still need this to handle automated builds/deployments in different build environments.
