### ISSUE TITLE
Rewrite readme in form of a specification for apps

### ISSUE THREAD

**Issue by alexvanin** [nspcc-dev/neofs-http-gw#216]
- [x] Describe all endpoints HTTP gateway provides
- [x] Describe all headers HTTP gateway processes
- [x] Describe all request parameters and options

**Comment by alexvanin** [comment]
- [ ] Mention in README special symbol rewriting (attribute `d@te` is valid as `d%40te`).

**Comment by KirillovDenis** [comment]
Blocked by #229
