### ISSUE TITLE
Floating error, Put objects using HTTP with attribute - code = 4096 message = session token not found

### ISSUE THREAD

**Issue by acheyda** [nspcc-dev/neofs-http-gw#224]
Floating error, Put objects using HTTP with attribute - code = 4096 message = session token not found

## Expected Behavior
```
'http://obj-nn-test-node2.spb.yadro.com:81/upload/BCCzdUR4Fiy28TJtZRfWhG8y8kJr9sffLW9pdEoeZRwr'
RESPONSE:
 {'object_id': '9QbV9wEhLL9mMMGkRgyEVEpHJydDWe7pLCDbS9cpwVcS', 'container_id': 'BCCzdUR4Fiy28TJtZRfWhG8y8kJr9sffLW9pdEoeZRwr'}
```

## Current Behavior
```
 Failed to get object via HTTP gate:
                request: /upload/BCCzdUR4Fiy28TJtZRfWhG8y8kJr9sffLW9pdEoeZRwr,
                response: could not store file in neofs: init writing on API client: client failure: status: code = 4096 message = session token not found, status code: 400 Bad Request
```

## Steps to Reproduce (for bugs)

1.Create Container
2.Upload via HTTP Gate
```
Failed to get object via HTTP gate:
                request: /upload/BCCzdUR4Fiy28TJtZRfWhG8y8kJr9sffLW9pdEoeZRwr,
                response: could not store file in neofs: init writing on API client: client failure: status: code = 4096 message = session token not found, status code: 400 Bad Request
```

## Your Environment
NeoGo
Version: 0.99.3-2-gaa57779d
GoVersion: go1.18.4
NeoFS CLI
Version: v0.33.0-27-g7d456cb4 
GoVersion: go1.18.4
NeoFS Adm
Version: v0.33.0-27-g7d456cb4 
GoVersion: go1.18.4

[obj-nn-test-node2.spb.yadro.com-http_gate-log.txt](https://github.com/nspcc-dev/neofs-node/files/9898553/obj-nn-test-node2.spb.yadro.com-http_gate-log.txt)
[obj-nn-test-node2.spb.yadro.com-ir01-log.txt](https://github.com/nspcc-dev/neofs-node/files/9898596/obj-nn-test-node2.spb.yadro.com-ir01-log.txt)

**Comment by KirillovDenis** [comment]
It also would be nice to see http-gw config

**Comment by KirillovDenis** [comment]
Actually it can be normal behavior on node restart (we need to check this in storage node logs)

In sdk pool we can cache old tokens that become invalid sometimes and we should recreated them.  
https://github.com/nspcc-dev/neofs-sdk-go/blob/7a2a76af95a7b9ff59155583f79c43c58ed5303d/pool/pool.go#L1644
https://github.com/nspcc-dev/neofs-sdk-go/blob/7a2a76af95a7b9ff59155583f79c43c58ed5303d/pool/pool.go#L1843

**Comment by acheyda** [comment]
Sorry, I forgot to add.
NeoFS HTTP Gateway
Version: v0.24.0-17-g1b172e58
GoVersion: go1.18.4

**Comment by alexvanin** [comment]
> Actually it can be normal behavior on node restart (we need to check this in storage node logs)

Agree. With @acheyda we tried to find some node restart messages but didn't find any. Storage node logs are still appreciated in this issue.

**Comment by acheyda** [comment]
[obj-nn-test-node2.spb.yadro.com-s03-log.txt](https://github.com/nspcc-dev/neofs-http-gw/files/9921273/obj-nn-test-node2.spb.yadro.com-s03-log.txt)
[obj-nn-test-node2.spb.yadro.com-coredns-log.txt](https://github.com/nspcc-dev/neofs-http-gw/files/9921282/obj-nn-test-node2.spb.yadro.com-coredns-log.txt)
[obj-nn-test-node2.spb.yadro.com-s02-log.txt](https://github.com/nspcc-dev/neofs-http-gw/files/9921285/obj-nn-test-node2.spb.yadro.com-s02-log.txt)
[obj-nn-test-node2.spb.yadro.com-s01-log.txt](https://github.com/nspcc-dev/neofs-http-gw/files/9921292/obj-nn-test-node2.spb.yadro.com-s01-log.txt)
[obj-nn-test-node2.spb.yadro.com-s04-log.txt](https://github.com/nspcc-dev/neofs-http-gw/files/9921306/obj-nn-test-node2.spb.yadro.com-s04-log.txt)

**Comment by KirillovDenis** [comment]
What about http-gw config?

**Comment by acheyda** [comment]
Here is what we are adding to the stand. (During the test run, the config does not change)
https://b.yadro.com/projects/OBJ/repos/morph-control/browse/env/neofs/group_vars/neofs/neofs-http-gw.yml?at=refs%2Fheads%2Fsbercloud-auto
This one comes from the guys from morph. 
https://github.com/nspcc-dev/neofs-http-gw/blob/master/config/config.yaml
That is, in what arrived from the morph, we added what I sent in the 1st link and put it on the stand

**Comment by alexvanin** [comment]
This bug haven't seen in november nightly tests (there were a few of them). Keep looking :eyes:

**Comment by alexvanin** [comment]
Let's wait till beginning of december.

**Comment by alexvanin** [comment]
We've seen some node restarts with https://github.com/nspcc-dev/neofs-node/issues/2095 (not sure it is related to restart, though). This error is expected in case of storage node restart without [persistent_session.path](https://github.com/nspcc-dev/neofs-node/blob/816c74d1857f2f0940af27da029413b3716c2eeb/config/example/node.yaml#L29)
