### ISSUE TITLE
Modified time for object in zip archive

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-http-gw#227]
Should we use time from `Timestamp` attribute?
https://github.com/nspcc-dev/neofs-http-gw/blob/131f2dbcfc1d247ce2430c3cdb6eee84eca1d0bf/downloader/download.go#L393-L397

If so what we should do if such an attribute is missing or invalid?
I think we can continue to use `time.Now()` for more consistency.

**Comment by alexvanin** [comment]
Let's find out what users may expect from ctime in zip archive.

**Comment by alexvanin** [comment]
We should document current behaviour and reopen this issue after additional requirements.

**Comment by KirillovDenis** [comment]
https://github.com/nspcc-dev/neofs-http-gw/blob/7b1410968e66f7d692eec2bcc977eb4a6ca0204b/docs/api.md?plain=1#L280

**Comment by alexvanin** [comment]
Done, see https://github.com/nspcc-dev/neofs-http-gw/issues/227#issuecomment-1324805441
