### ISSUE TITLE
Support network settings' requests

### ISSUE THREAD

**Issue by cthulhu-rider** [nspcc-dev/neofs-http-gw#275]
there is no way to get NeoFS network settings via HTTP gateway

**Describe the solution you'd like**
```http
GET /network HTTP/1.1
```
```http
HTTP/1.1 200 OK
Content-Type: application/json

{
  "epochDuration": 240,
  "storagePrice":100000
}
```

**Describe alternatives you've considered**
no other ideas

**Additional context**
* will be useful for https://github.com/nspcc-dev/fs-neo-org/issues/1

**Comment by roman-khimov** [comment]
It's a dead end, IIRC REST already has it.

**Comment by roman-khimov** [comment]
Not going to be implemented.
