### ISSUE TITLE
Could not upload file using Bearer token

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/neofs-http-gw#53]
Could not upload file using **__context_bearer_token_key** cookie

## Expected Behavior
File should be uploaded

## Current Behavior
Error: could not store file in neofshttps://github.com/nspcc-dev/neofs-http-gw/blob/master/tokens/bearer-token.go#L43

## Possible Solution
Using correct key **__context_bearer_token_key** instead of **Bearer** when getting Bearer token from cookies in file https://github.com/nspcc-dev/neofs-http-gw/blob/master/tokens/bearer-token.go#L43

## Steps to Reproduce 

1. Create container with basic-acl **0x0FFFCFFF** 
2. Add eacl 
```
{
    "version": {
        "major": 0,
        "minor": 0
    },
    "containerID": {
        "value": "DhdPJjRwQdai1INIXNCSPYKaVTi593elLLFejYqu1Jw="
    },
    "records": [
        {
            "operation": "PUT",
            "action": "DENY",
            "filters": [],
            "targets": [
                {
                    "role": "OTHERS",
                    "keys": []
                }
            ]
        }
    ]
}
```
3. Try upload file using valid Bearer token
`curl -F 'file=@text.txt;filename=test.txt' -b '__context_bearer_token_key=CoABClsKABIiCiAOF08mNHBB1qLUg0hc0JI9gppVOLn3d6UssV6Niq7UnBopCAMQARofCAIQARoFRW1haWwiEnNhbXBsZUBleGFtcGxlLmNvbSICCAMaCAgDEAIiAggDEhsKGTUmhNW417iYnYEyxKySWbzH3MdCNBnnOCwaBAjQhgMSZgohAxpsb7vfAso1F0X6hrm6WpRS14WsT3/Ct1SMoqRsT89KEkEErdsKPqvVmVQvJpfAahDdv2mQh046qgv+ycikTYD0DBeWXhORNUidseug+VWT3zC4PBRMA+VGYxbqKecytvRdiQ=='  -H 'X-Attribute-Email: sample@example.com' http://localhost:8082/upload/x1Khy3scKfefEZG2CYauK3GVH4vhb9vqrE3auAs8UGK`

## Context
If at step 3 above use **Bearer**  instead of  **__context_bearer_token_key** it works correct

log neofs-http-gw
![image](https://user-images.githubusercontent.com/11478618/120614813-4d6fa900-c460-11eb-825d-06c8bc1b8714.png)

## Your Environment

* Version used: 0.15.1
* Server setup and configuration: neofs-node version 0.20.0 from [neofs-dev-env](https://github.com/nspcc-dev/neofs-dev-env)
* Operating System and version (`uname -a`): Linux denis 5.6.0-1056-oem #60-Ubuntu SMP Tue May 4 06:40:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by roman-khimov** [comment]
`__context_bearer_token_key` is used for request context internally, I think we can just update the README here.
