### ISSUE TITLE
Support "Content-Type" well-known attribute

### ISSUE THREAD

**Issue by roman-khimov** [nspcc-dev/neofs-http-gw#65]
We're autodetecting Content-Type header at the moment even though we have well-known `AttributeContentType` defined for objects. HTTP gate should take and use that if it's defined for an object (and fallback to autodetection otherwise) the same way it does for `FileName` and `Timestamp` attributes at the moment.

**Comment by realloc** [comment]
There is a well-known attribute [Content-Type](https://github.com/nspcc-dev/neofs-api/blob/v2.7.0/object/types.proto#L127) defined for this.
