### ISSUE TITLE
HEAD verb should be supported

### ISSUE THREAD

**Issue by realloc** [nspcc-dev/neofs-http-gw#76]
HTTP `HEAD` verb should be translated into the NeoFS HEAD on object. The same API path set should accept both `GET` and `HEAD`

**Comment by alexvanin** [comment]
What response do you expect to see on `HEAD` request? JSON encoded headers?

**Comment by realloc** [comment]
By default it has to return the plain http HEAD response. 

The issue arises when http HEAD comes to the nginx reverse proxy, it has to make the full GET, cache the result and return only HEAD to the. client.

JSON output might be a  good feature, we could switch the output format depending on the client's Accept headers preferences.
